version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metacatalog
    expose:
      - 5432
    ports:
      - 5433:5432
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
  
  installer:
    # use the version v0.5.0 for the image
    image: ghcr.io/vforwater/tbr_vforwater_loader:v0.5.0
    depends_on:
      - db
    links:
      - db
    environment:
      METACATALOG_URI: postgresql://postgres:postgres@db:5432/metacatalog
      DATA_FILE_PATH: /data/raster
      START_YEAR: 1980
      END_YEAR: 1990
    volumes:
      - ./data/raster:/data/raster
      - ./init:/tool_init
    command: ["python", "/src/pg_init/init.py"]

